"""remove language from data chunks

Revision ID: b22c28a9066d
Revises: a7f3c1d92b48
Create Date: 2026-08-16 15:22:03.082641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b22c28a9066d'
down_revision: Union[str, Sequence[str], None] = 'a7f3c1d92b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_chunks', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_chunks', sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
